name = "CausalDynamics"
uuid = "a1b2c3d4-e5f6-7890-abcd-ef1234567890"
version = "0.1.0"
authors = ["CDCS Book Contributors"]
repo = "https://github.com/SimonAB/CausalDynamics.jl.git"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"

[compat]
# Allow latest compatible versions of all dependencies
# Using major version constraints to allow automatic updates within major versions
DataFrames = "1"
Documenter = "1"
ForwardDiff = "1"
Graphs = "1"
# Allow latest versions: ModelingToolkit 9.x, 10.x, 11.x (and future major versions)
ModelingToolkit = "9, 10, 11"
# Allow latest versions: Symbolics 6.x, 7.x (and future major versions)
Symbolics = "6, 7"
julia = "1.12"

[extras]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
GraphMakie = "1ecd5474-83a3-4783-bb4f-06765db800d2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
docs = ["Documenter"]
test = ["Test", "CairoMakie", "DataFrames", "GraphMakie"]
